### ISSUE TITLE
Compile warnings while installation

### ISSUE THREAD

**Issue by jcs090218** [godotengine/emacs-gdscript-mode#98] opened 2020-10-25 05:33 UTC
I got the following compile warnings.

**OS:** Windows x64
**Emacs version:** `27.1`

```
In toplevel form:
gdscript-debug.el:1871:1:Warning: Unused lexical variable `server-process'
gdscript-debug.el:1887:1:Warning: Unused lexical variable `server-process'

In gdscript-debug--many-windows:
gdscript-debug.el:2152:39:Warning: reference to free variable `lv-wnd'
gdscript-debug.el:2398:1:Warning: `"n"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"c"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"m"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"s"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"b"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"v"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"i"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"t"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"d"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"o"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"u"' is a malformed function
gdscript-debug.el:2398:1:Warning: `"q"' is a malformed function
gdscript-debug.el:2400:13:Warning: reference to free variable
    `gdscript-debug--hydra'
gdscript-debug.el:2400:13:Warning: `:hint' called as a function
gdscript-debug.el:2400:42:Warning: reference to free variable `none'

In end of data:
gdscript-debug.el:2423:1:Warning: the following functions are not known to be
    defined: do-applescript, defhydra, :hint, gdscript-debug--hydra/body

In end of data:
gdscript-hydra.el:155:1:Warning: the function `gdscript-hydra--menu/body' is
    not known to be defined.

In gdscript-info-dedenter-opening-block-positions:
gdscript-indent-and-nav.el:716:24:Warning: `seq-contains' is an obsolete
    function (as of 27.1); use `seq-contains-p' instead.

In gdscript-project--select-scene:
gdscript-project.el:52:111:Warning: `format' called with 1 args to fill 0
    format field(s)

In end of data:
gdscript-project.el:116:1:Warning: the function `ag-project-regexp' is not
    known to be defined.
```

**Comment by NathanLovato** [comment] 2021-10-04 12:21
Duplicate of #87

**Closed by NathanLovato** 2021-10-04 12:21 UTC
Labels: bug
